import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import RecoilRootWrapper from "@/app/RecoilWrapper";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`bg-gray-50 text-gray-950 p-2 flex justify-center items-center ${inter.className}`}>
      <RecoilRootWrapper>
        {children}
        <Toaster/>
      </RecoilRootWrapper>
      </body>
    </html>
  )
}
